# Deployment of Smart3
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: hpe-dps
  name: hpe-dps
  labels:
    app: hpe-dps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hpe-dps
  template:
    metadata:
      labels:
        app: hpe-dps
    spec:
      containers:
        - name: hpe-dps
          image: harbor.datasvc01.lysdemolab.fr/jear/cloud3-dsp:v1.40
          resources:
            requests: 
              cpu: "250m"
              memory: "64Mi"
            limits:
              cpu : "500m"
              memory: "512Mi"
          ports:
            - name: hpe-dps-web
              containerPort: 80    
          imagePullPolicy: Always  
          volumeMounts:
            - name: nginx-default-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-default-config
          configMap:
            name: defaultnginx
